services:
  - type: web
    name: essence-ui-webhook
    env: node
    root: chromatic-webhook
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
